name: nextjs-go-template
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
